### ISSUE TITLE
TODO examples

### ISSUE THREAD

**Issue by davidmball** [davidmball/ros_examples#1]
This is a list of ideas for examples.

## msgs
- [ ] simple example
- [ ] dependencies
- [ ] custom msgs

## launch files
- [ ] simple
- [ ] conditionals

## Diagnostics
- [ ] Simple rates, etc
- [ ] custom

## TF
- [ ] Simple example of tf / tf2 (cpp, python)
- [ ] tf listeners / buffers
- [ ] interpolation / not extrapolation
- [ ] (Many) Show the different types of multiplications. Getting the order correct.

## robot_localisation
